### PR TITLE
Attempt to fix build of version 1.17

### PR DESCRIPTION
**Pull request by marcelm**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [X] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

The old version LDC 0.17.6 is compiled for bootstrapping since more recent compiler versions require a D compiler to be available. LDC 0.17.6 is only compatible with LLVM up to version 7.

### CODE REVIEW

**Comment by marcelm** [comment]
So this actually fixes the build on macOS and Linux. No idea why the Windows build fails.

Ping @brainstorm @bgruening

**Comment by marcelm** [comment]
The problem is that conda build has gained the ability to unpack 7-zip files, which means that the manual unpacking step fails in `bld.bat`.

**Comment by brainstorm** [comment]
Thanks for the refresh @marcelm! IIRC the windows build has been historically quite problematic (when we first put together this feedstock). Feel free to skip the window builds if you run out of ideas, we ended up doing that.

**Comment by marcelm** [comment]
Thanks, this is good to know. Then I’ll limit the time I spend on the Windows build.

**Comment by marcelm** [comment]
Ha! A little bit of finetuning, and it should be good to go :-)

**Comment by marcelm** [comment]
Sorry for the noise, but the version for which the build passed still copied some stray files from the build environment into the final package. And it’s been a long time since I wrote a batch script.

**Comment by marcelm** [comment]
This is now ready for merging.

**Comment by marcelm** [comment]
Thanks :-)

**Pull request merged**
