### PR TITLE
Try to build LDC 1.28.0

### PR DESCRIPTION
**Pull request by dpryan79**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dpryan79** [comment]
@conda-forge-admin please rerender

**Comment by dpryan79** [comment]
OSX issue: https://forum.dlang.org/thread/qnnsb3$3o2$1@digitalmars.com?page=1

**Comment by dpryan79** [comment]
@brainstorm @conda-forge/core This is ready for review. I presume there's a more proper way of getting libllvm12 as a run-time dependency.

**Comment by dpryan79** [comment]
@wolfv Since you started down this same route a couple months ago, perhaps you can have a look too.

**Comment by wolfv** [comment]
Wow, this looks great to me! I just checked the `libllvm` and `llvmdev` packages here https://github.com/conda-forge/llvmdev-feedstock/blob/master/recipe/meta.yaml and many seem to have a `run_exports`. Maybe we can depend on e.g. `llvm` or `llvmdev` in the `host` env and that should add the proper `run_exports` to the run environment on `libllvm + {{ major_version }} x.x`

But I am also no expert in the llvm packaging story.

**Comment by wolfv** [comment]
PS: Happy to merge when you're ready!

**Comment by dpryan79** [comment]
@wolfv Bereit, seems both llvm and llvmdev together did the trick.

**Pull request merged**
