### PR TITLE
Tweak aarch64 build.sh

### PR DESCRIPTION
**Pull request by corneliusroemer**
- **migration: ArchRebuild**
- **MNT: Re-rendered with conda-build 24.5.1, conda-smithy 3.36.1, and conda-forge-pinning 2024.06.12.07.10.11**
- **Special handle linux-aarch64 instead of osx-64, to be able to bootstrap**
- **Bump the build number to 1**
- **Try with cross-compilation for Linux aarch64 and ppc64le**
- **MNT: Re-rendered with conda-build 24.5.1, conda-smithy 3.36.1, and conda-forge-pinning 2024.06.12.07.10.11**
- **Fix the check for aarch64**
- **Try older version of ldc**
- **Use latest version of ldc2 that works with glibc 2.17**

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by corneliusroemer** [comment]
@conda-forge-admin, please rerender

**Comment by corneliusroemer** [comment]
@conda-forge-admin, please rerender

**Comment by corneliusroemer** [comment]
Sweet, it works for aarch64!

Power pc is much less used, so I will disable for now.

**Comment by martin-g** [comment]
Awesome!
Thank you, @corneliusroemer !

**Comment by corneliusroemer** [comment]
@martin-g Thank you for shepherding the whole aarch64 migration across conda-forge and bioconda!

Now let's try the same with osx-arm64!

**Pull request merged**
