### PR TITLE
Update LDC to 1.38

### PR DESCRIPTION
**Pull request by martin-g**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
@conda-forge-admin, please ping team

**Comment by martin-g** [comment]
@conda-forge/core Could someone please help with review and merge of this PR ? Thanks!

**Review by h-vetinari — APPROVED** [review]
Note that your clangdev cap here is severely outdated, and should be lifted as soon as possible/feasible.

**Comment by h-vetinari** [comment]
Thanks for willing to take on the maintenance here!

**Comment by h-vetinari** [comment]
Ah, you forgot to rerender after https://github.com/conda-forge/ldc-feedstock/pull/39/commits/b297dbe5f47fbe70f21ff923c1eedbf5cd3e885d... I'll push a fix to give you the required rights.

**Pull request merged**
