### PR TITLE
Arch migrate

### PR DESCRIPTION
**Pull request by martin-g**
This is a clone of https://github.com/conda-forge/ldc-feedstock/pull/37

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by corneliusroemer** [comment]
Thanks for your efforts @martin-g! As a motivation to get ldc ready for aarch64, it would enable tsv-utils to build for aarch64 :) 
https://github.com/conda-forge/tsv-utils-feedstock

Your last attempt failed because of glibc not being sufficiently high:

```
CMake Error at cmake/Modules/ExtractDMDSystemLinker.cmake:42 (message):
  Failed to link empty D program using
  '/home/conda/dlang/ldc-1.38.0/bin/ldmd2 -wi':

  /home/conda/dlang/ldc-1.38.0/bin/ldc2: /lib64/libm.so.6: version
  `GLIBC_2.27' not found (required by /home/conda/dlang/ldc-1.38.0/bin/ldc2)

  /home/conda/dlang/ldc-1.38.0/bin/ldc2: /lib64/libm.so.6: version
  `GLIBC_2.29' not found (required by /home/conda/dlang/ldc-1.38.0/bin/ldc2)

  /home/conda/dlang/ldc-1.38.0/bin/ldc2: /lib64/libc.so.6: version
  `GLIBC_2.18' not found (required by /home/conda/dlang/ldc-1.38.0/bin/ldc2)
Call Stack (most recent call first):
  CMakeLists.txt:643 (include)
```

**Comment by corneliusroemer** [comment]
Trying a fix in this PR: #42 

The last ldc2 binary to support glibc 2.17 was v1.26.0, so using that one.

**Pull request merged**
